/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface SearchConfig {
  topK?: number
  similarityThreshold?: number
}
export declare function indexProject(workspacePath: string, excludePatterns?: Array<string> | undefined | null): Promise<number>
export declare function cancelIndexProject(workspacePath: string): void
export declare function getIndexStats(workspacePath: string): string
export declare function searchCode(workspacePath: string, query: string, topK: number, config?: SearchConfig | undefined | null): Promise<string>
/**
 * Evaluates a ranked fixture without loading the embedding model. This is used
 * by CI relevance gates to detect retrieval regressions deterministically.
 */
export declare function evaluateRanking(rankedJson: string, relevanceJson: string, k: number): string
export declare function hybridSearch(workspacePath: string, query: string, config?: SearchConfig | undefined | null): Promise<string>
